version: '3'
services:
  db:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: 'photo-db'
      MYSQL_USER: 'photo'
      MYSQL_PASSWORD: 'photo'
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  mysql-data:
    driver: local
